apiVersion: batch/v1
kind: CronJob
metadata: 
  name: nodejs-cronjob
  labels:
    name: nodejs-cronjob
spec:
  schedule: "* * * * *"  
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: nodejs-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: nodejs-cronjob
              image: nodejs-job:latest