apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-match-expression
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
      - key: environment
        operator: In
        values:
          - production
          - staging
          - qa
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        environment: production
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80